In [1]:
for i in range(100,10000):
    pass

In [4]:
for i in range(1,10):
    i==5
    print(i)
    continue

1
2
3
4
5
6
7
8
9


In [5]:
for i in range(1,10):
    if i==5:
        continue
    print(i)

1
2
3
4
6
7
8
9


In [6]:
for i in 'Maharashtra':
    if i== 'h':
        continue
    print(i)

M
a
a
r
a
s
t
r
a


### Break

In [7]:
for i in range(40,80):
    if i==41:
        break
    print(i)

40


# Numpy

In [2]:
import numpy

In [9]:
!pip install numpy

In [3]:
arr=numpy.array([12,45,87,41])

In [4]:
arr

array([12, 45, 87, 41])

In [14]:
type(arr)

numpy.ndarray

In [12]:
numpy.sqrt(arr)

array([3.46410162, 6.70820393, 9.32737905, 6.40312424])

In [15]:
import numpy as np

### 0D Array

In [16]:
arr1=np.array(25)

In [17]:
arr1

array(25)

In [18]:
type(arr1)

numpy.ndarray

In [19]:
arr1.ndim

0

### 1 D Array

In [20]:
arr11=np.array([12,47,85,96,58,74])

In [21]:
type(arr11)

numpy.ndarray

In [22]:
arr11.ndim

1

### 2 D Array

In [23]:
arr12=np.array([[1,2,3],[5,6,8],[9,8,5]])

In [24]:
arr12.ndim

2

### Access 1 D array

In [25]:
lst=[89,74,56,98,25,41]
arr13=np.array(lst)

In [27]:
arr13.ndim

1

In [28]:
arr13[0]

89

In [29]:
arr13[3]

98

In [30]:
arr13[-3]

98

In [31]:
arr13[1:4]

array([74, 56, 98])

### Access 2 D Array

In [32]:
arr14=np.array([[45,54,65],
                [74,14,85],
                [96,78,42]])

In [33]:
arr14.ndim

2

In [34]:
arr14[1]

array([74, 14, 85])

In [36]:
arr14[1,1]

14

In [37]:
arr14[1,0:2]

array([74, 14])

### Arithmatic operation

In [38]:
arr21=np.array([25,63,98,74,56])
arr22=np.array([55,77,44,88,55])

In [40]:
arr21+arr22

array([ 80, 140, 142, 162, 111])

In [41]:
arr21-arr22

array([-30, -14,  54, -14,   1])

In [42]:
arr21/arr22

array([0.45454545, 0.81818182, 2.22727273, 0.84090909, 1.01818182])

In [43]:
arr21**2

array([ 625, 3969, 9604, 5476, 3136], dtype=int32)

In [44]:
arr23=np.array([75,35,64,73,95])
arr24=np.array([64,92,76,91,82,75])

In [45]:
arr23+arr24

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [46]:
arr23-arr24

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [47]:
arr23

array([75, 35, 64, 73, 95])

In [48]:
np.sqrt(arr23)

array([8.66025404, 5.91607978, 8.        , 8.54400375, 9.74679434])

In [49]:
arr=np.array(3)

In [50]:
arr11=np.array([1,2])

In [51]:
arr+arr11

array([4, 5])

In [52]:
from numpy import random

### Randint()

In [58]:
np.random.randint(100)

27

In [60]:
np.random.randint(1,50)

14

In [61]:
np.random.randint(1,60,20)

array([ 7, 31, 58, 24, 15, 12, 56, 53, 49, 30, 44, 35,  9, 34, 37, 45, 53,
       20, 17, 29])

In [62]:
np.random.randint(2,10,(5,5))

array([[5, 8, 9, 4, 2],
       [5, 3, 7, 4, 9],
       [8, 8, 9, 9, 6],
       [6, 5, 8, 2, 5],
       [9, 7, 2, 3, 8]])

In [63]:
np.random.randint('A','Z')

ValueError: invalid literal for int() with base 10: 'A'

In [67]:
arrr=np.array(np.arange(1,26)).reshape(5,5)

In [68]:
arrr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [69]:
arrr=np.array(np.arange(1,26)).reshape(5,6)

ValueError: cannot reshape array of size 25 into shape (5,6)

In [72]:
arr31=np.array(np.arange(1,26),dtype=float).reshape(5,5)

In [73]:
arr31

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

### Randn()

In [77]:
np.random.randn()

-1.8597228875912035

In [79]:
np.random.randn(50)

array([ 0.71680263,  0.71609703, -1.34360692, -0.28494957,  1.05896584,
        0.13173327,  0.91374437,  1.21812403, -0.07743796,  1.0080586 ,
       -0.61308866, -0.10963027,  0.93824463, -1.80862638, -1.39833229,
       -1.67474625, -0.52322627, -0.64138141, -2.42936108,  0.95823229,
        0.85867103, -1.54316183, -1.57326123,  1.08097324,  1.7952521 ,
       -0.10377111,  0.07621988, -0.02046613,  0.50947916, -0.45262415,
        0.64563535,  0.63834307, -0.43740507,  1.56688152, -0.73764572,
        0.60345938, -1.96270485, -0.10164711, -0.95082993, -1.51251196,
       -1.56451178, -0.61641454, -0.59631104, -0.09782362,  0.18853741,
       -0.25952147,  1.15831595, -2.37043509,  0.41656356,  0.72484864])

### rand

In [81]:
np.random.rand(15)

array([0.19786105, 0.83565825, 0.41660527, 0.59529829, 0.43505685,
       0.7015794 , 0.17081459, 0.76298898, 0.26450367, 0.45376766,
       0.3343535 , 0.0291478 , 0.19974213, 0.14956112, 0.49474566])

### linspace

In [84]:
np.linspace(1,10,11)

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [86]:
np.linspace(20,21,10)

array([20.        , 20.11111111, 20.22222222, 20.33333333, 20.44444444,
       20.55555556, 20.66666667, 20.77777778, 20.88888889, 21.        ])

### Choice

In [89]:
list1=[1,2,3,4,5,6]

In [91]:
np.random.choice(list1)

2

In [96]:
np.random.choice([10,20,30,40],p=[0.80,0,0,0.20])

10

In [97]:
np.random.randrange(10)

AttributeError: module 'numpy.random' has no attribute 'randrange'

In [98]:
import random

In [100]:
random.randrange(100)

29

In [101]:
random.randrange(10,50)

35

### Shuffle

In [154]:
a=np.arange(6)

In [155]:
np.random.shuffle(a)

In [156]:
a

array([5, 0, 1, 3, 2, 4])

In [148]:
arr = np.arange(10)
np.random.shuffle(arr)



In [149]:
arr

array([9, 7, 4, 6, 3, 8, 1, 5, 0, 2])