In [1]:
import numpy as np

### Shuffle

In [2]:
ar=np.array([1,5,47,8,9,6,5,3])

In [7]:
np.random.shuffle(ar)

In [8]:
ar

array([ 3,  6, 47,  8,  9,  5,  5,  1])

### seed

In [25]:
np.random.seed(100)
np.random.randint(10,60,11)

array([18, 34, 13, 49, 33, 25, 58, 20, 40, 44, 12])

In [36]:
np.random.seed(101)
np.random.randint(100,1000,20)

array([963, 623, 437, 938, 675, 699, 175, 493, 652, 744, 675, 857, 416,
       832, 804, 210, 105, 577, 140, 149])

### Function in Numpy

In [37]:
arr=np.array([78,45,96,35,15,47])

In [38]:
arr

array([78, 45, 96, 35, 15, 47])

### SQRT

In [39]:
np.sqrt(arr)

array([8.83176087, 6.70820393, 9.79795897, 5.91607978, 3.87298335,
       6.8556546 ])

### CBRT

In [41]:
arr

array([78, 45, 96, 35, 15, 47])

In [40]:
np.cbrt(arr)

array([4.27265868, 3.5568933 , 4.57885697, 3.27106631, 2.46621207,
       3.60882608])

### Varience

In [43]:
var=np.var(arr)

In [44]:
var

723.5555555555557

In [45]:
np.sqrt(var)

26.89898800244269

In [46]:
np.std(arr)

26.89898800244269

In [47]:
np.log(arr)

array([4.35670883, 3.80666249, 4.56434819, 3.55534806, 2.7080502 ,
       3.8501476 ])

In [48]:
arr

array([78, 45, 96, 35, 15, 47])

In [49]:
np.max(arr)

96

In [50]:
np.min(arr)

15

In [51]:
np.sum(arr)

316

In [52]:
ar1=np.array([25,47,86,91,73])
ar2=np.array([42,53,62,51,55])

In [54]:
ar1+ar2

array([ 67, 100, 148, 142, 128])

In [55]:
np.add(ar1,ar2)

array([ 67, 100, 148, 142, 128])

In [56]:
ar1-ar2

array([-17,  -6,  24,  40,  18])

In [57]:
np.subtract(ar1,ar2)

array([-17,  -6,  24,  40,  18])

In [58]:
ar1*ar2

array([1050, 2491, 5332, 4641, 4015])

In [59]:
np.multiply(ar1,ar2)

array([1050, 2491, 5332, 4641, 4015])

In [60]:
ar1/ar2

array([0.5952381 , 0.88679245, 1.38709677, 1.78431373, 1.32727273])

In [61]:
np.divide(ar1,ar2)

array([0.5952381 , 0.88679245, 1.38709677, 1.78431373, 1.32727273])

### abs

In [62]:
abs(-10)

10

In [63]:
np.abs(-42)

42

In [64]:
np.absolute(-526)

526

In [65]:
absolute(-5)

NameError: name 'absolute' is not defined

### Where

In [68]:
arr2=np.arange(10,30)

In [69]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [70]:
np.where(arr2>15)

(array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       dtype=int64),)

In [71]:
np.where([True,False],[10,20],[30,40])

array([10, 40])

In [72]:
np.where([False,False,True,False],[10,20,30,40],[50,60,70,80])

array([50, 60, 30, 80])

In [73]:
arr=np.array([74,52,15,48,66,33])
arr1=np.array([55,44,78,69,14,78])

In [74]:
np.where(arr>50,arr,arr1)

array([74, 52, 78, 69, 66, 78])

### Concatenate

In [76]:
a=np.array([[44,11,52],
            [85,96,74]])

b=np.array([[52,35,42],
            [65,45,85]])

In [79]:
np.concatenate((a,b))

array([[44, 11, 52],
       [85, 96, 74],
       [52, 35, 42],
       [65, 45, 85]])

In [78]:
np.concatenate((a,b),axis=1)

array([[44, 11, 52, 52, 35, 42],
       [85, 96, 74, 65, 45, 85]])

### Stack
- Join a sequence of arrays along a new axis.

In [80]:
a

array([[44, 11, 52],
       [85, 96, 74]])

In [81]:
b

array([[52, 35, 42],
       [65, 45, 85]])

In [82]:
np.stack((a,b))

array([[[44, 11, 52],
        [85, 96, 74]],

       [[52, 35, 42],
        [65, 45, 85]]])

### vstack
- Stack arrays in sequence vertically (row wise).

In [83]:
a

array([[44, 11, 52],
       [85, 96, 74]])

In [84]:
b

array([[52, 35, 42],
       [65, 45, 85]])

In [85]:
np.vstack((a,b))

array([[44, 11, 52],
       [85, 96, 74],
       [52, 35, 42],
       [65, 45, 85]])

### hstack
- Stack arrays in sequence horizontally (column wise).

In [86]:
a

array([[44, 11, 52],
       [85, 96, 74]])

In [87]:
b

array([[52, 35, 42],
       [65, 45, 85]])

In [88]:
np.hstack((a,b))

array([[44, 11, 52, 52, 35, 42],
       [85, 96, 74, 65, 45, 85]])

### Dstack
- Stack arrays in sequence depth wise (along third axis).

In [89]:
a

array([[44, 11, 52],
       [85, 96, 74]])

In [90]:
b

array([[52, 35, 42],
       [65, 45, 85]])

In [91]:
np.dstack((a,b))

array([[[44, 52],
        [11, 35],
        [52, 42]],

       [[85, 65],
        [96, 45],
        [74, 85]]])

### split array

In [92]:
aa=np.arange(1,10)

In [93]:
aa

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
np.split(aa,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [97]:
a,b,c=np.split(aa,3)

In [98]:
a

array([1, 2, 3])

In [99]:
b

array([4, 5, 6])

In [100]:
c

array([7, 8, 9])

### hsplit

In [101]:
r=np.array([41,52,65,45,85,75,99,82,41,63])

In [102]:
r

array([41, 52, 65, 45, 85, 75, 99, 82, 41, 63])

In [104]:
np.hsplit(r,1)

[array([41, 52, 65, 45, 85, 75, 99, 82, 41, 63])]

In [105]:
np.hsplit(r,2)

[array([41, 52, 65, 45, 85]), array([75, 99, 82, 41, 63])]

In [107]:
np.hsplit(r,5)

[array([41, 52]),
 array([65, 45]),
 array([85, 75]),
 array([99, 82]),
 array([41, 63])]

In [108]:
r

array([41, 52, 65, 45, 85, 75, 99, 82, 41, 63])

In [115]:
arr2d=np.array([[10,20],[30,40],[50,60],[70,80]])

In [116]:
np.vsplit(arr2d,2)

[array([[10, 20],
        [30, 40]]),
 array([[50, 60],
        [70, 80]])]

In [117]:
np.vsplit(arr2d,4)

[array([[10, 20]]), array([[30, 40]]), array([[50, 60]]), array([[70, 80]])]

In [118]:
np.vsplit(arr2d,5)

ValueError: array split does not result in an equal division