<img src="fireblaze.jpg" width=150 height=100 />

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("salary-data.csv")

In [3]:
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

# EDA

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes


In [5]:
data.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [6]:
data.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [7]:
data.corr()

YearsExperience    Salary
YearsExperience         1.000000  0.978242
Salary                  0.978242  1.000000

In [8]:
# Take Independant and Dependant variable

In [9]:
X = data.iloc[:,[0]].values   # 2D
# X = data['YearsExperience'].values    # Same as Above

In [10]:
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [11]:
Y = data['Salary'].values      # 1D

In [12]:
Y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [13]:
# Split the data into traning and testing part 

In [14]:
data.shape

(30, 2)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.20,random_state=0)

# 0.20 menas testing data is 20 % and 80 % training
# random satate for to select data randomly into training and testing part 

In [17]:
print(X_train.shape)
print(Y_train.shape)

(24, 1)
(24,)


In [18]:
print(X_test.shape)
print(Y_test.shape)

(6, 1)
(6,)


### Apply Linear Regression 

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
Regression = LinearRegression()     # Fit Linear Regression in variable

In [21]:
# Fit the training data 
Regression.fit(X_train,Y_train)

LinearRegression()

##### Show Model Coef Value

In [22]:
Regression.intercept_    # B0 Value

26780.09915062818

In [23]:
Regression.coef_     # B1 value 

array([9312.57512673])

In [24]:
Y_test

array([ 37731., 122391.,  57081.,  63218., 116969., 109431.])

In [25]:
# Prediction on testing data 
Y_pred = Regression.predict(X_test)

In [26]:
Y_pred   # Predicted values

array([ 40748.96184072, 122699.62295594,  64961.65717022,  63099.14214487,
       115249.56285456, 107799.50275317])

In [27]:
# Evaluate Model

### R2

In [28]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [29]:
R2_score = r2_score(Y_test,Y_pred)
R2_score

0.988169515729126

### MAE,MSE,RMSE

In [30]:
print(mean_absolute_error(Y_test,Y_pred))

2446.1723690465055


In [31]:
print(mean_squared_error(Y_test,Y_pred))

12823412.298126549


In [32]:
print(np.sqrt(mean_squared_error(Y_test,Y_pred)))

3580.979237321343


In [33]:
### Prediction 

In [34]:
print(Regression.predict([[2]]))   # Prediction for 2 Year EXP

[45405.24940409]


# END