<img src="fireblaze.jpg" width=250 height=150 />


## Table of Content

1. **[Numpy Array](#Array)**
2. **[Numpy Function](#Function)**
3. **[Pandas Series & DataFrame](#Pandas)**
4. **[Datetime Module](#Datetime)**

# <p style="font-family: Arial; font-size:1.4em;color:red; style='background :yellow'"> Assignment</p>


<a id="Array"></a>
## Numpy Array

### <span style='color:Blue'> **Question - 1. Write a program to create an Array:** </span>
1. Create 10 X 10 array of numbers starting from 0.01 to 1.0.
2. Create a boolean array
3. Create an array of values between 0 to 1 with 20 equal spacings.
4. Create a 5 x 5 matrics of values between 0 to 26

In [1]:
# Importing useful Libraries
import numpy as np

In [2]:
# Answer 1.1) 10 X 10 array of numbers starting from 0.01 to 1.0.


arr=np.arange(0.01,1.01,0.01).reshape(10,10)
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [3]:
# Answer 1.2) a boolean array


arr1=np.ones((2,5),dtype=bool)
# arr0=np.zeros((2,5),dtype=bool)
print(arr1)
# print(arr0)

[[ True  True  True  True  True]
 [ True  True  True  True  True]]


In [4]:
# Answer 1.3) An array of values between 0 to 1 with 20 equal spacings.

arr2=np.linspace(0,1,21)
arr2

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [5]:
# Answer 1.4) a 5 x 5 matrics of values between 0 to 26


arr3=np.arange(1,26).reshape(5,5)
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### <span style='color:Blue'> **Question - 2. Identify real and imaginary numbers from the given array.** </span>

* x = np.sqrt([1+0j])
* y = np.sqrt([0+1j])

In [6]:
#write observation and code here

### <span style='color:Blue'> **Question - 3. How can change the shape without changing the data in an array?** </span>

NOTE:- 
•Take array as x = np.array([1, 2, 3, 4, 5, 6]).reshape(3,2)
•Convert x in 2x3 from 3x2 shape


In [7]:
x = np.array([1, 2, 3, 4, 5, 6]).reshape(2,3)
print(x)

[[1 2 3]
 [4 5 6]]


### <span style='color:Blue'> **Question - 4. Write a progarm to create a 5 x 5 Array. and then exchage data of 1st column with 3rd column without changing the data in an array?** </span>

In [8]:
#write observation and code here

### <span style='color:Blue'> **Question - 5. Perform Arithmatic operation on given array?** </span>

In [9]:
#write observation and code here

<a id="Function"></a>
## Numpy Function

### <span style='color:Blue'> **Question - 6. Calculate:** </span>
1. std
2. mean
3. median
4. std
5. sqrt
6. cbrt
7. sum
**Note :** Use given array

In [10]:
#write observation and code here

### <span style='color:Blue'> **Question - 7. Create two 2D numpy array and concat it** </span>

In [11]:
#write observation and code here

### <span style='color:Blue'> **Question - 8.Create two 2D array and stack it column wise** </span>

In [12]:
#write observation and code here

### <span style='color:Blue'> **Question - 9. How to extract items that satisfy a given condition from 1D array?** </span>

In [13]:
#write observation and code here

### <span style='color:Blue'> **Question - 10. From the given array access the elements that match the desired output?** </span>

<a id="Pandas"></a>
## Pandas Series & DataFrame

### <span style='color:Blue'> **Question - 11.Create a Dataframe with columns name ID','Name','City','Sub1_mark','sub2_mark' after creating Dataframe add New column ('Total Mark') to a DataFrame where use sum of 'Sub1_mark' & 'Sub2_mark' as the element** </span>


In [14]:
#write observation and code here

### <span style='color:Blue'> **Question - 12. Write a progam to create a Series of 10 random numbers between 25 to 50, with index as A,B,C ... J.** </span>

In [15]:
#write observation and code here

### <span style='color:Blue'> **Question - 13. Write a program to create a DataFrame of consisting of 2 columns which column 1 of values 10 values between 25 to 50 and Column 2 of have 10 alphabets starting from A,B,C...J.** </span>

**NOTE** Columns name is col1 and col2

In [16]:
#write observation and code here

### <span style='color:Blue'> **Question - 14. Write a program to create a Series of 35 numbers between 1 to 10 in a series and then convert it into a table format of 7 rows and 5 columns and display** </span>

In [17]:
#write observation and code here

### <span style='color:Blue'> **Question - 15. Create a Dataframe using the following data and solve the tasks** </span>

* **'age' :**     [ 10, 22, 13, 21, 12, 11, 17],
* **'section' :** [ 'A', 'B', 'C', 'B', 'B', 'A', 'A'],
* **'city' :**    [ 'Gurgaon', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai'],
* **'gender' :**  [ 'M', 'F', 'F', 'M', 'M', 'M', 'F'],
* **'favourite_color' :** [ 'red', np.NAN, 'yellow', np.NAN, 'black', 'green', 'red']

* **Task**

Problem 1:- How many examples whose age is greater than equal to 15?

Problem 2:- How many males whose age greater than equal to 12.
    
Problem 3:- Print top five example of section and gender.
    
Problem 4:- Print 0 and 2 number of example of section and gender.

In [18]:
#write observation and code here

### <span style='color:Blue'> **Question - 16. Create a DataFrame with Hierarchy index.** </span>

In [19]:
#write observation and code here

### <span style='color:Blue'> **Question - 17. Create a DataFrame with random numbers and take a sum of two column i.e. W and Y, those output save in new column.** </span>

In [20]:
#write observation and code here

 ### <span style='color:Blue'> **Question - 18. Using above dataframe add new column i.e. column name is States with values CA, NY, WY, OR, CO and set that column as an index.** </span>

In [21]:
#write observation and code here

### <span style='color:Blue'> **Question - 19.Combine the following dataframe using concatenate.** </span>

In [22]:
#write observation and code here

### <span style='color:Blue'> **Question - 20.After concatenate upper two DataFrame, Check any duplicate row present in the DataFrame.If any duplicate row present then drop it .** </span>

In [23]:
### write observation and code here

### <span style='color:Blue'> **Question - 21.Merge below two DataFrame by 'section column in the right DataFrame.** </span>
**Note:** Perform operation:
- Inner
- Outer
- Left
- Right


Right DataFrame
* **'age' :**     [ 10, 22, 13, 21, 12, 11, 17],
* **'section' :** [ 'A', 'B', 'C', 'B', 'B', 'A', 'A'],
* **'city' :**    [ 'Gurgaon', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai'],
* **'gender' :**  [ 'M', 'F', 'F', 'M', 'M', 'M', 'F'],
* **'favourite_color' :** [ 'red', np.NAN, 'yellow', np.NAN, 'black', 'green', 'red']

Left DataFrame
* **'age' :**     [ 10, 22, 13, 21, 12, 11, 17],
* **'section' :** [ 'B', 'B', 'A', 'B', 'C', 'A', 'C'],
* **'city' :**    [ 'Gurgaon', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai'],
* **'gender' :**  [ 'M', 'F', 'F', 'M', 'M', 'M', 'F'],
* **'favourite_color' :** [ 'red', np.NAN, 'yellow', np.NAN, 'black', 'green', 'red']

In [24]:
#write observation and code here

### <span style='color:Blue'> **Question - 22.Create a DtataFrame using given key & value pair then create a group of A & C  and perform all aggregate function on it.**</span>

In [25]:
#write observation and code here

<a id="Datetime"></a>
# Datetime Module

### <span style='color:Blue'> **Question - 23.How to display a current date.** </span>
**Note :** Use DateTime Module function

In [26]:
#write observation and code here

### <span style='color:Blue'> **Question - 24.How to print :.** </span>
- Weekday with full version 
- Weekday with short version 
- Month name short version 
- Month name full version
**Note :** Use DateTime Module function

In [27]:
#write observation and code here

### <span style='color:Blue'> **Question - 25.Print Current year & weekday** </span>
**Note :** Use DateTime Module function

In [28]:
#write observation and code here

# End